-- 先创建数据库（如果不存在）
CREATE DATABASE IF NOT EXISTS village_committee CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 使用数据库
USE village_committee;

-- 村民表
CREATE TABLE IF NOT EXISTS residents (
  id BIGINT NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  id_card VARCHAR(18) NULL,
  phone VARCHAR(20) NULL,
  address VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 公告表
CREATE TABLE IF NOT EXISTS announcements (
  id BIGINT NOT NULL AUTO_INCREMENT,
  title VARCHAR(100) NOT NULL,
  content TEXT NOT NULL,
  publisher VARCHAR(50) NOT NULL,
  publish_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



-- 访问记录（管理后台访问趋势统计）
CREATE TABLE IF NOT EXISTS visit_events (
  id BIGINT NOT NULL AUTO_INCREMENT,
  visited_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  path VARCHAR(255) NOT NULL,
  method VARCHAR(10) NOT NULL,
  status INT NOT NULL,
  took_ms INT NOT NULL,
  request_id VARCHAR(36) NULL,
  PRIMARY KEY (id),
  KEY idx_visit_time (visited_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
